### PR TITLE
Create github issue template (PLEASE READ)

### PR DESCRIPTION
**Pull request by sgdc3**
Use "THERMOS IS NO LONGER BEING DEVELOPED. IF YOU MAKE AN ISSUE, IT WILL NOT BE RESOLVED AND WILL JUST BE CLOSED." as default issue content.

### CODE REVIEW

**Comment by sgdc3** [comment]
@Time6628

**Comment by djoveryde** [comment]
I would suggest cloning this repository and continuing the project yourself if you want to continue work as they will only deny and close it :(

**Comment by KasperFranz** [comment]
His commit here is only to tell people that they can't create issues basically :9

**Comment by sgdc3** [comment]
@Time6628

**Comment by sgdc3** [comment]
@Time6628

**Comment by sgdc3** [comment]
@Time6628 READ BEFORE CLOSING

**Pull request closed without merging**
