### PR TITLE
Removed FlatMap to improve performance

### PR DESCRIPTION
**Pull request by dogboy21**

### CODE REVIEW

**Comment by Robotia** [comment]
Hello,

What kind of performance improvements did you see with this change?

Thanks,

Robotia

**Comment by dogboy21** [comment]
Unfortunately I don't have any screenshots from the WarmRoast measurement yesterday, but the initialization of a FlatMap took about 30% of the server load on one of our servers. 

TPS Graph 
Here you can see the TPS graph of said server. You see the jump in the middle of the graph? Thats the time when I updated the server to the fixed version. Overall we noticed improvements of about 2-5 TPS on every of our 30 servers. Also the FlatMap was removed ages ago from Spigot because of memory leaks and other performance problems as you can see [here](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/util/LongObjectHashMap.java) and [here](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/util/LongHashSet.java)

**Comment by iKaneki-Ken** [comment]
@dogboy21 Thank you for this! Honestly, thank you!

**Comment by usernameak** [comment]
Side effect: WorldEdit //regen doesn't work

**Comment by dogboy21** [comment]
I think //regen was broken for a long time on modded servers.
Are you sure that this PR is causing the problem? IIRC it only added a patch which was part of Spigot for a long time.

**Comment by sameer** [comment]
Was about to note this as well -- are you using the world edit plugin? If I
am remembering correctly, they did develop a forge oriented version of it
as a mod.

**Comment by SantaGitHub** [comment]
@usernameak use this patch for thermos 58 https://yadi.sk/d/4KrI2qYp3RDAgV

**Pull request merged**
