### PR TITLE
Gradlew update

### PR DESCRIPTION
**Pull request by ArcasCZ**
Updated gradlew to make build possible (certificate problems with old gradlew)

### CODE REVIEW

**Comment by ArcasCZ** [comment]
Also fixed lib dependency.

**Comment by Time6628** [comment]
Just use sponge.

**Comment by ArcasCZ** [comment]
Sponge is useless until it will support Spigot / Bukkit plugins or untill will be on Sponge atleast 10% of Spigot plugins...

**Comment by Time6628** [comment]
https://github.com/Maxqia/PoreRT There's a sponge plugin that allows bukkit/spigot plugins to run on sponge.

**Comment by JTLWebDesign** [comment]
Pore has pretty well been abandoned though

**Comment by Eufranio** [comment]
^

**Comment by JTLWebDesign** [comment]
Oh wait, Time's link appears to be a reboot of it. Maybe there could be some potential here. It does appear though that it is not anywhere close to ready to use yet though

**Comment by Brend-Smits** [comment]
Good luck porting Thermos to 1.10.2 lol... Sponge is already more stable then Thermos at this point.
It's just a matter of time before majority of the other big plugins port their work to Sponge. You're better off porting other plugins to Sponge then making Thermos 1.10. Will save you a lot of time and effort.

**Comment by JTLWebDesign** [comment]
The community I am a part of has one server running Sponge on 1.10.2 and it is HORRIBLE. I have less almost 0 issues with the 2 servers I am in charge of running Thermos, but the Sponge server is always having problems. I understand part of that is the modpack itself, but many of the issues that I have looked into going on there are directly related to Sponge not being that good yet.

**Comment by Brend-Smits** [comment]
So instead of making an updated version of Thermos 1.10.2 (which will take you a very a long time), why not just contribute to Sponge and provide them with visualvm profiles / timings / warmroast reports or even pull requests to make the project better?

btw: There is a new test build out, this will DRASTICALLY increase the performance on for example SF3 servers and DW20 servers. 
There were lots of issues with chunkloading, which have been fixed in that build.

**Comment by ArcasCZ** [comment]
'cause they are bunch of idiots (except few people). Look at this: https://forums.spongepowered.org/t/switching-online-mode/17496/7

That's reason I'd rather port Thermos with help of my friends...

**Comment by Brend-Smits** [comment]
I don't see anything wrong with the post you linked. They are not insulting you in any way o0 
But fine, if you would rather port Thermos then improve Sponge, go right ahead ^^ 

All I have to say is ... Good luck.... lol

**Comment by ArcasCZ** [comment]
They just talk about supporting cracked servers or not - but that's not question I asked. If I'll go to Sponge, I'll do cracked server anyway. But I asked them with help to give premium users oppinion to log-in without password and better protect their acc. And they are still talking about online-mode=true/false...

**Comment by Time6628** [comment]
It's easier to port plugins than it is Thermos itself. Just port AuthMe or whatever to sponge.

Also, forge is all patch files so have fun with that of you decide to port Thermos.

**Comment by ArcasCZ** [comment]
AuthMe is so hard to port, but I can write small own plugin based on AuthMe DB - that's not the problem. Problem are missing libraries such as ProtoclLib / ProtocolSupport and functions from them.

**Comment by sgdc3** [comment]
As an AuthMe dev i can confirm it would require a complete rewrite of the plugin.

**Comment by sgdc3** [comment]
I never tried using AuthMe on pore, it would be interesting ;)

**Comment by Time6628** [comment]
Why would you need ProtocolLib? If you're using spongeforge you can call forge methods right from your plugin.

**Comment by ArcasCZ** [comment]
'Cause lot of things you can't call directly and with ProtocolLib it's more easy - look at FastLogin for example.

**Pull request closed without merging**
